export interface Lesson {
  id: string;
  title: string;
  description: string;
  content: string;
  duration: number;
  type: 'intro' | 'content' | 'interactive' | 'challenge' | 'reflection';
  points: number;
  requiredForBadge?: string;
}

export interface Module {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  lessons: Lesson[];
  badge: { id: string; name: string; icon: string; description: string };
  certificate: { id: string; name: string; description: string };
  estimatedTime: number;
}

export const complete50LessonModules: Module[] = [
  {
    id: 'sustainability',
    title: 'Introduction to Sustainability',
    description: 'Foundation concepts of sustainable development',
    icon: '🌍',
    color: 'from-green-400 to-emerald-500',
    estimatedTime: 6,
    badge: { id: 'sustainability-champion', name: 'Sustainability Champion', icon: '🏆', description: 'Master of sustainability principles' },
    certificate: { id: 'sustainability-cert', name: 'Sustainability Specialist', description: 'Certified in sustainable development' },
    lessons: [
      { id: 'sus-1', title: 'What is Sustainability?', description: 'Understanding the concept of sustainability and its importance', content: 'Generated by Gemini API', duration: 45, type: 'intro', points: 50 },
      { id: 'sus-2', title: 'The Three Pillars of Sustainability (People, Planet, Profit)', description: 'Foundation of sustainable development', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 75 },
      { id: 'sus-3', title: 'Why Sustainability Matters for the Future', description: 'Long-term impacts and benefits', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'sus-4', title: 'Sustainable Development Goals (SDGs)', description: 'UN SDGs and their global impact', content: 'Generated by Gemini API', duration: 55, type: 'interactive', points: 80 },
      { id: 'sus-5', title: 'Everyday Sustainability Practices', description: 'Simple actions for sustainable living', content: 'Generated by Gemini API', duration: 35, type: 'reflection', points: 65, requiredForBadge: 'sustainability-champion' }
    ]
  },
  {
    id: 'renewable-energy',
    title: 'Renewable Energy',
    description: 'Clean energy sources and sustainable power generation',
    icon: '⚡',
    color: 'from-yellow-400 to-orange-500',
    estimatedTime: 12,
    badge: { id: 'energy-expert', name: 'Energy Expert', icon: '🔋', description: 'Leader in renewable energy' },
    certificate: { id: 'renewable-cert', name: 'Renewable Energy Specialist', description: 'Expert in clean energy technologies' },
    lessons: [
      { id: 're-1', title: 'Introduction to Renewable Energy', description: 'Overview of clean energy sources', content: 'Generated by Gemini API', duration: 40, type: 'intro', points: 60 },
      { id: 're-2', title: 'Solar Power – The Energy from the Sun', description: 'Harnessing solar energy for power generation', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 're-3', title: 'Wind Energy – Harnessing the Wind', description: 'Wind turbines and wind power systems', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 're-4', title: 'Hydropower – Power from Water', description: 'Water-based electricity generation', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 're-5', title: 'Biomass Energy – Nature\'s Recycling', description: 'Energy from organic materials', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 're-6', title: 'Geothermal Energy – Heat from Earth', description: 'Using Earth\'s internal heat for energy', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 're-7', title: 'Tidal & Wave Energy – Power of Oceans', description: 'Marine renewable energy sources', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 're-8', title: 'Nuclear Power – Clean but Controversial', description: 'Nuclear energy pros and cons', content: 'Generated by Gemini API', duration: 50, type: 'interactive', points: 80 },
      { id: 're-9', title: 'Comparing Renewable Energy Sources', description: 'Analysis of different renewable technologies', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 're-10', title: 'The Future of Renewable Energy', description: 'Emerging technologies and trends', content: 'Generated by Gemini API', duration: 40, type: 'reflection', points: 70, requiredForBadge: 'energy-expert' }
    ]
  },
  {
    id: 'non-renewable-energy',
    title: 'Non-Renewable Energy',
    description: 'Understanding finite energy sources and their impacts',
    icon: '🛢️',
    color: 'from-gray-500 to-slate-600',
    estimatedTime: 5,
    badge: { id: 'energy-analyst', name: 'Energy Analyst', icon: '📊', description: 'Expert in energy resource analysis' },
    certificate: { id: 'non-renewable-cert', name: 'Energy Resource Specialist', description: 'Certified in non-renewable energy systems' },
    lessons: [
      { id: 'nre-1', title: 'What are Non-Renewable Energy Resources?', description: 'Understanding finite energy sources', content: 'Generated by Gemini API', duration: 40, type: 'intro', points: 60 },
      { id: 'nre-2', title: 'Coal: The Black Gold and Its Problems', description: 'Coal mining, usage, and environmental impact', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'nre-3', title: 'Oil and Natural Gas: Dependence and Pollution', description: 'Petroleum products and their effects', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'nre-4', title: 'Environmental Costs of Non-Renewables', description: 'Pollution and climate impacts', content: 'Generated by Gemini API', duration: 40, type: 'interactive', points: 70 },
      { id: 'nre-5', title: 'Transition from Non-Renewable to Renewable Energy', description: 'Energy transition strategies', content: 'Generated by Gemini API', duration: 45, type: 'reflection', points: 75, requiredForBadge: 'energy-analyst' }
    ]
  },
  {
    id: 'carbon-climate',
    title: 'Carbon & Climate',
    description: 'Understanding climate change and carbon impacts',
    icon: '🌫️',
    color: 'from-blue-400 to-indigo-500',
    estimatedTime: 8,
    badge: { id: 'climate-defender', name: 'Climate Defender', icon: '🛡️', description: 'Guardian against climate change' },
    certificate: { id: 'climate-cert', name: 'Climate Change Specialist', description: 'Expert in climate science and solutions' },
    lessons: [
      { id: 'cc-1', title: 'Carbon Emissions Explained', description: 'Understanding carbon dioxide and greenhouse gases', content: 'Generated by Gemini API', duration: 45, type: 'intro', points: 70 },
      { id: 'cc-2', title: 'Carbon Footprint: Measuring Our Impact', description: 'Personal and organizational carbon assessment', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'cc-3', title: 'Greenhouse Effect & Global Warming', description: 'Climate science and warming mechanisms', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'cc-4', title: 'Climate Change: Causes and Effects', description: 'Climate impacts and consequences', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'cc-5', title: 'Carbon Sequestration – Storing Carbon Safely', description: 'Carbon capture and storage technologies', content: 'Generated by Gemini API', duration: 40, type: 'interactive', points: 70 },
      { id: 'cc-6', title: 'International Agreements on Climate (Paris Agreement, etc.)', description: 'Global cooperation on climate action', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'cc-7', title: 'Net Zero Future – What Does It Mean?', description: 'Achieving carbon neutrality', content: 'Generated by Gemini API', duration: 40, type: 'reflection', points: 70, requiredForBadge: 'climate-defender' }
    ]
  },
  {
    id: 'pollution',
    title: 'Environmental Pollution',
    description: 'Comprehensive study of pollution types and solutions',
    icon: '🏭',
    color: 'from-red-400 to-orange-500',
    estimatedTime: 18,
    badge: { id: 'pollution-fighter', name: 'Pollution Fighter', icon: '🛡️', description: 'Defender against environmental pollution' },
    certificate: { id: 'pollution-cert', name: 'Environmental Protection Specialist', description: 'Expert in pollution control and prevention' },
    lessons: [
      { id: 'pol-1', title: 'Introduction to Pollution', description: 'Types and sources of environmental pollution', content: 'Generated by Gemini API', duration: 40, type: 'intro', points: 60 },
      { id: 'pol-2', title: 'Air Pollution: Causes, Effects, and Solutions', description: 'Atmospheric contamination and control', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'pol-3', title: 'Water Pollution: Causes, Effects, and Solutions', description: 'Water contamination and treatment', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'pol-4', title: 'Soil Pollution: Causes, Effects, and Solutions', description: 'Land contamination and remediation', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'pol-5', title: 'Noise Pollution and Its Impact', description: 'Sound pollution and health effects', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'pol-6', title: 'Plastic Pollution: A Global Menace', description: 'Plastic waste and marine pollution', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'pol-7', title: 'Thermal Pollution: Heating Our Waters', description: 'Temperature-based environmental damage', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'pol-8', title: 'Radioactive Pollution: Hidden Dangers', description: 'Nuclear contamination and safety', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'pol-9', title: 'Light Pollution: Losing the Night Sky', description: 'Artificial lighting and ecological impacts', content: 'Generated by Gemini API', duration: 35, type: 'content', points: 65 },
      { id: 'pol-10', title: 'E-Waste: The Digital Age Waste Problem', description: 'Electronic waste management', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'pol-11', title: 'Urban Pollution and Cities', description: 'City-specific environmental challenges', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'pol-12', title: 'Agricultural Pollution (Pesticides, Fertilizers)', description: 'Farming-related environmental impacts', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'pol-13', title: 'Industrial Pollution and Its Control', description: 'Manufacturing waste and regulation', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'pol-14', title: 'Household Pollution (Chemicals, Waste)', description: 'Domestic sources of contamination', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'pol-15', title: 'Pollution Prevention and Green Technologies', description: 'Clean technology solutions', content: 'Generated by Gemini API', duration: 45, type: 'reflection', points: 75, requiredForBadge: 'pollution-fighter' }
    ]
  },
  {
    id: 'conservation',
    title: 'Conservation & Nature',
    description: 'Protecting and restoring natural ecosystems',
    icon: '🌳',
    color: 'from-emerald-400 to-green-600',
    estimatedTime: 10,
    badge: { id: 'nature-guardian', name: 'Nature Guardian', icon: '🦋', description: 'Protector of natural ecosystems' },
    certificate: { id: 'conservation-cert', name: 'Conservation Specialist', description: 'Expert in environmental conservation' },
    lessons: [
      { id: 'con-1', title: 'Deforestation: Causes and Consequences', description: 'Forest loss and environmental impact', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'con-2', title: 'Afforestation & Reforestation: Healing the Earth', description: 'Forest restoration and tree planting', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'con-3', title: 'Biodiversity and Why It Matters', description: 'Species diversity and ecosystem health', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'con-4', title: 'Conservation of Water Resources', description: 'Water management and protection', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'con-5', title: 'Sustainable Agriculture', description: 'Eco-friendly farming practices', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'con-6', title: 'Waste Management & Recycling', description: 'Circular economy and waste reduction', content: 'Generated by Gemini API', duration: 50, type: 'interactive', points: 80 },
      { id: 'con-7', title: 'Energy Efficiency & Smart Living', description: 'Reducing energy consumption', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'con-8', title: 'Future of Sustainability: Youth as Change-Makers', description: 'Next generation environmental leadership', content: 'Generated by Gemini API', duration: 45, type: 'reflection', points: 75, requiredForBadge: 'nature-guardian' }
    ]
  },
  {
    id: 'green-technology',
    title: 'Green Technology & Innovation',
    description: 'Cutting-edge technologies for environmental solutions',
    icon: '🔧',
    color: 'from-cyan-400 to-blue-500',
    estimatedTime: 12,
    badge: { id: 'tech-innovator', name: 'Tech Innovator', icon: '💡', description: 'Pioneer in green technology' },
    certificate: { id: 'green-tech-cert', name: 'Green Technology Specialist', description: 'Expert in environmental technology solutions' },
    lessons: [
      { id: 'gt-1', title: 'Introduction to Green Technology', description: 'Overview of environmental technology solutions', content: 'Generated by Gemini API', duration: 40, type: 'intro', points: 60 },
      { id: 'gt-2', title: 'Smart Grids: Powering the Future', description: 'Intelligent electricity distribution systems', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'gt-3', title: 'Electric Vehicles & Transportation', description: 'Sustainable mobility solutions', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'gt-4', title: 'AI for Climate Solutions', description: 'Artificial intelligence in environmental protection', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'gt-5', title: 'IoT in Energy Management', description: 'Internet of Things for energy efficiency', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'gt-6', title: 'Green Buildings & Smart Cities', description: 'Sustainable urban development', content: 'Generated by Gemini API', duration: 50, type: 'content', points: 80 },
      { id: 'gt-7', title: 'Recycling Technologies & E-Waste Management', description: 'Advanced waste processing systems', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'gt-8', title: 'Clean Manufacturing & Industry 4.0', description: 'Sustainable industrial processes', content: 'Generated by Gemini API', duration: 50, type: 'interactive', points: 80 },
      { id: 'gt-9', title: 'Future of Renewable Tech (Hydrogen, Fusion, etc.)', description: 'Next-generation energy technologies', content: 'Generated by Gemini API', duration: 45, type: 'content', points: 75 },
      { id: 'gt-10', title: 'Youth & Innovation: Green Startups', description: 'Entrepreneurship in environmental technology', content: 'Generated by Gemini API', duration: 40, type: 'reflection', points: 70, requiredForBadge: 'tech-innovator' }
    ]
  },
  {
    id: 'sustainable-lifestyles',
    title: 'Sustainable Lifestyles & Communities',
    description: 'Building eco-friendly communities and personal habits',
    icon: '🏡',
    color: 'from-pink-400 to-purple-500',
    estimatedTime: 10,
    badge: { id: 'lifestyle-champion', name: 'Lifestyle Champion', icon: '🌟', description: 'Leader in sustainable living' },
    certificate: { id: 'sustainable-living-cert', name: 'Sustainable Living Specialist', description: 'Expert in eco-friendly lifestyle practices' },
    lessons: [
      { id: 'sl-1', title: 'Introduction to Sustainable Living', description: 'Foundations of eco-friendly lifestyle choices', content: 'Generated by Gemini API', duration: 35, type: 'intro', points: 60 },
      { id: 'sl-2', title: 'Zero Waste Lifestyle', description: 'Minimizing waste in daily life', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'sl-3', title: 'Minimalism: Less is More', description: 'Simplifying life for sustainability', content: 'Generated by Gemini API', duration: 35, type: 'content', points: 65 },
      { id: 'sl-4', title: 'Eco-Friendly Products in Daily Life', description: 'Choosing sustainable alternatives', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'sl-5', title: 'Community Farming & Urban Gardens', description: 'Local food production systems', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'sl-6', title: 'Sustainable Fashion & ReWear Culture', description: 'Ethical clothing and circular fashion', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'sl-7', title: 'Green Entrepreneurship', description: 'Building sustainable businesses', content: 'Generated by Gemini API', duration: 45, type: 'interactive', points: 75 },
      { id: 'sl-8', title: 'Role of Communities in Sustainability', description: 'Collective action for environmental change', content: 'Generated by Gemini API', duration: 40, type: 'content', points: 70 },
      { id: 'sl-9', title: 'Sustainable Food Choices', description: 'Eco-friendly eating habits', content: 'Generated by Gemini API', duration: 35, type: 'content', points: 65 },
      { id: 'sl-10', title: 'Building a Sustainable Future Together', description: 'Collaborative approaches to sustainability', content: 'Generated by Gemini API', duration: 40, type: 'reflection', points: 70, requiredForBadge: 'lifestyle-champion' }
    ]
  }
];

export const getAllLessons = () => complete50LessonModules.flatMap(module => module.lessons);
export const getLessonById = (lessonId: string) => getAllLessons().find(lesson => lesson.id === lessonId);
export const getModuleById = (moduleId: string) => complete50LessonModules.find(module => module.id === moduleId);
export const getModuleProgress = (moduleId: string, completedLessons: string[]) => {
  const module = getModuleById(moduleId);
  if (!module) return 0;
  const completedInModule = module.lessons.filter(lesson => completedLessons.includes(lesson.id)).length;
  return Math.round((completedInModule / module.lessons.length) * 100);
};